version: '3.8'

services:
  azote-sql:
    container_name: azote-sql
    image: mariadb:bionic
    restart: unless-stopped
    volumes:
      - 'datasqlghost:/var/lib/mysql'
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  azote-ghost:
    image: 'ghost:latest'
    container_name: azote-ghost
    restart: unless-stopped
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/timezone:/etc/timezone:ro'
      - 'dataghost:/var/lib/ghost/content'
      - './conf/config.production.json:/var/lib/ghost/config.production.json:ro'
    labels:
      - traefik.enable=true
      - traefik.http.routers.ghost.entrypoints=http
      - traefik.http.routers.ghost.rule=Host(`portfolio.codeassist.io`)
      - traefik.http.routers.ghost-secure.entrypoints=https
      - traefik.http.routers.ghost-secure.rule=Host(`portfolio.codeassist.io`)
      - traefik.http.routers.ghost-secure.tls=true
      - traefik.http.routers.ghost-secure.tls.certresolver=letsencrypt
      - traefik.http.services.ghost.loadbalancer.server.port=2368
      - traefik.http.routers.ghost.middlewares=https-redirect@file
      - traefik.http.routers.ghost-secure.middlewares=compression@file, security@file
      - traefik.docker.network=hydrogen
    depends_on:
      - azote-sql

volumes:
  datasqlghost:
  dataghost:
