version: '3.8'

services:
  azote-sql:
    container_name: azote-sql
    image: mariadb:bionic
    restart: always
    command: --sql-mode=""
    volumes:
      - 'datasqlghost:/var/lib/mysql'
    networks:
      - hydrogen
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  azote-ghost:
    image: 'ghost:3'
    container_name: azote-ghost
    restart: always
    networks:
      - hydrogen
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/timezone:/etc/timezone:ro'
      - 'dataghost:/var/lib/ghost/content'
      - './conf/config.production.json:/var/lib/ghost/config.production.json:ro'
    labels:
      - traefik.enable=true
      - traefik.http.routers.ghost.entrypoints=http
      - traefik.http.routers.ghost.rule=Host(`portfolio.codeassist.io`)
      - traefik.http.routers.ghost-secure.entrypoints=https
      - traefik.http.routers.ghost-secure.rule=Host(`portfolio.codeassist.io`)
      - traefik.http.routers.ghost-secure.tls=true
      - traefik.http.routers.ghost-secure.tls.certresolver=letsencrypt
      - traefik.http.services.ghost.loadbalancer.server.port=2368
      - traefik.http.routers.ghost.middlewares=https-redirect@file
      - traefik.http.routers.ghost-secure.middlewares=compression@file, security@file
      - traefik.docker.network=hydrogen
    depends_on:
      - azote-sql

networks:
  hydrogen:
    external: true

volumes:
  datasqlghost:
  dataghost:
